# Generated by Django 5.2.8 on 2025-11-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter Name', max_length=20)),
                ('order_id', models.IntegerField(help_text='Enter ID')),
                ('date_of_order', models.DateField()),
                ('date_of_delivery', models.DateField()),
            ],
        ),
    ]
